source "https://rubygems.org"

ruby '3.2.0'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'minitest'
gem 'rubocop', '1.51', require: false
gem 'bcrypt'
gem 'rack-test'
gem 'erubis'
group :production do
  gem "puma"
end