source "https://rubygems.org"

ruby "3.0.2"

gem "sinatra"
gem "sinatra-contrib"
gem "erubis"
gem 'rubocop', '1.51', require: false
gem 'rack-test'
gem 'minitest'
gem 'redcarpet'
gem 'bcrypt'
group :production do
  gem "puma"
end